{
		"pid":0,
		"pname":"cocos",
		"pversion":"1.0.0", 
		"ppath":"animation.txt",
		"pagecount":6,
		"page":[
			{
				"id":0,
				"name":"locker", 
				"spirits":[ 
							{
								"spirit_id":1,
								"spirit_name":"sprites_2D_background_1" 
							},
							{
								"spirit_id":2,
								"spirit_name":"sprites_2D_background_2"
							},
							{
								"spirit_id":3,
								"spirit_name":"sprites_2D_heart_1"
							},
							{
								"spirit_id":4,
								"spirit_name":"sprites_2D_flower_1"
							},
							{
								"spirit_id":5,
								"spirit_name":"sprites_2D_flower_top"
							},
							{
								"spirit_id":6,
								"spirit_name":"sprites_2D_butterfly_1"
							},
							{
								"spirit_id":7,
								"spirit_name":"sprites_2D_curtain_1"
							},
							{
								"spirit_id":8,
								"spirit_name":"sprites_2D_flower_right_1"
							},
							{
								"spirit_id":9,
								"spirit_name":"sprites_2D_icon_red_1"
							},
							{
								"spirit_id":10,
								"spirit_name":"sprites_2D_icon_red_2"
							},
							{
								"spirit_id":11,
								"spirit_name":"sprites_2D_icon_red_3"
							},
							{
								"spirit_id":12,
								"spirit_name":"sprites_2D_icon_red_4"
							},
							{
								"spirit_id":13,
								"spirit_name":"sprites_2D_icon_red_5"
							},
							{
								"spirit_id":14,
								"spirit_name":"sprites_2D_icon_red_6"
							},
							{
								"spirit_id":15,
								"spirit_name":"sprites_2D_icon_red_7"
							},
							{
								"spirit_id":16,
								"spirit_name":"sprites_2D_icon_red_8"
							},
							{
								"spirit_id":17,
								"spirit_name":"sprites_2D_label_red_1"
							},
							{
								"spirit_id":18,
								"spirit_name":"sprites_2D_label_red_2"
							},
							{
								"spirit_id":19,
								"spirit_name":"sprites_2D_label_white_1"
							},
							{
								"spirit_id":20,
								"spirit_name":"sprites_2D_label_white_2"
							},
							{
								"spirit_id":21,
								"spirit_name":"sprites_2D_box_yellow"
							},
							{
								"spirit_id":22,
								"spirit_name":"sprites_2D_box_red"
							},
							{
								"spirit_id":38,
								"spirit_name":"sprites_2D_light_1"
							},
							{
								"spirit_id":81,
								"spirit_name":"sprites_2D_star_1"
							}
						]
			},
			{
				"id":1,
				"name":"unlock", 
				"spirits":[ 
							{
								"spirit_id":1,
								"spirit_name":"sprites_2D_background_1" 
							},
							{
								"spirit_id":2,
								"spirit_name":"sprites_2D_background_2"
							},
							{
								"spirit_id":3,
								"spirit_name":"sprites_2D_heart_1"
							},
							{
								"spirit_id":4,
								"spirit_name":"sprites_2D_flower_1"
							},
							{
								"spirit_id":5,
								"spirit_name":"sprites_2D_flower_top"
							},
							{
								"spirit_id":6,
								"spirit_name":"sprites_2D_butterfly_1"
							},
							{
								"spirit_id":7,
								"spirit_name":"sprites_2D_curtain_1"
							},
							{
								"spirit_id":8,
								"spirit_name":"sprites_2D_flower_right_1"
							},
							{
								"spirit_id":9,
								"spirit_name":"sprites_2D_icon_red_1"
							},
							{
								"spirit_id":10,
								"spirit_name":"sprites_2D_icon_red_2"
							},
							{
								"spirit_id":11,
								"spirit_name":"sprites_2D_icon_red_3"
							},
							{
								"spirit_id":12,
								"spirit_name":"sprites_2D_icon_red_4"
							},
							{
								"spirit_id":13,
								"spirit_name":"sprites_2D_icon_red_5"
							},
							{
								"spirit_id":14,
								"spirit_name":"sprites_2D_icon_red_6"
							},
							{
								"spirit_id":15,
								"spirit_name":"sprites_2D_icon_red_7"
							},
							{
								"spirit_id":16,
								"spirit_name":"sprites_2D_icon_red_8"
							},
							{
								"spirit_id":17,
								"spirit_name":"sprites_2D_label_red_1"
							},
							{
								"spirit_id":18,
								"spirit_name":"sprites_2D_label_red_2"
							},
							{
								"spirit_id":19,
								"spirit_name":"sprites_2D_label_white_1"
							},
							{
								"spirit_id":20,
								"spirit_name":"sprites_2D_label_white_2"
							},
							{
								"spirit_id":21,
								"spirit_name":"sprites_2D_box_yellow"
							},
							{
								"spirit_id":22,
								"spirit_name":"sprites_2D_box_red"
							}

				]
				
			},
			{
				"id":2,
				"name":"homepage", 
				"spirits":[ 
							{
								"spirit_id":1,
								"spirit_name":"sprites_2D_background_1" 
							},
							{
								"spirit_id":2,
								"spirit_name":"sprites_2D_background_2"
							},
							{
								"spirit_id":3,
								"spirit_name":"sprites_2D_heart_1"
							},
							{
								"spirit_id":5,
								"spirit_name":"sprites_2D_flower_top"
							},
							{
								"spirit_id":6,
								"spirit_name":"sprites_2D_butterfly_1"
							},
							{
								"spirit_id":8,
								"spirit_name":"sprites_2D_flower_right_1"
							},
							{
								"spirit_id":22,
								"spirit_name":"sprites_2D_box_red"
							},
							{
								"spirit_id":23,
								"spirit_name":"sprites_2D_flower_2"
							},
							{
								"spirit_id":24,
								"spirit_name":"sprites_2D_flower_3"
							},
							{
								"spirit_id":25,
								"spirit_name":"sprites_2D_icon_yellow_1"
							},
							{
								"spirit_id":26,
								"spirit_name":"sprites_2D_icon_yellow_2"
							},
							{
								"spirit_id":27,
								"spirit_name":"sprites_2D_icon_yellow_3"
							},
							{
								"spirit_id":28,
								"spirit_name":"sprites_2D_icon_yellow_4"
							},
							{
								"spirit_id":29,
								"spirit_name":"sprites_2D_icon_yellow_5"
							},
							{
								"spirit_id":30,
								"spirit_name":"sprites_2D_icon_yellow_6"
							},
							{
								"spirit_id":31,
								"spirit_name":"sprites_2D_icon_yellow_7"
							},
							{
								"spirit_id":32,
								"spirit_name":"sprites_2D_icon_yellow_8"
							},
							{
								"spirit_id":33,
								"spirit_name":"sprites_2D_icon_purple_1"
							},
							{
								"spirit_id":34,
								"spirit_name":"sprites_2D_icon_purple_2"
							},
							{
								"spirit_id":35,
								"spirit_name":"sprites_2D_icon_purple_3"
							},
							{
								"spirit_id":36,
								"spirit_name":"sprites_2D_icon_purple_4"
							},
							{
								"spirit_id":37,
								"spirit_name":"sprites_2D_icon_sprites_1"
							}
				]
			},
			{
				"id":3,
				"name":"applist", 
				"spirits":[ 
							{
								"spirit_id":39,
								"spirit_name":"sprites_2D_background_3" 
							},
							{
								"spirit_id":40,
								"spirit_name":"sprites_2D_icon_white_1"
							},
							{
								"spirit_id":41,
								"spirit_name":"sprites_2D_icon_white_2"
							},
							{
								"spirit_id":42,
								"spirit_name":"sprites_2D_icon_white_3"
							},
							{
								"spirit_id":43,
								"spirit_name":"sprites_2D_icon_sprites_2"
							},
							{
								"spirit_id":44,
								"spirit_name":"sprites_2D_lable_a"
							},
							{
								"spirit_id":45,
								"spirit_name":"sprites_2D_lable_b"
							},
							{
								"spirit_id":46,
								"spirit_name":"sprites_2D_lable_c"
							},
							{
								"spirit_id":47,
								"spirit_name":"sprites_2D_lable_d"
							},
							{
								"spirit_id":48,
								"spirit_name":"sprites_2D_lable_e"
							},
							{
								"spirit_id":49,
								"spirit_name":"sprites_2D_lable_f"
							},
							{
								"spirit_id":50,
								"spirit_name":"sprites_2D_lable_g"
							},
							{
								"spirit_id":51,
								"spirit_name":"sprites_2D_lable_h"
							},
							{
								"spirit_id":52,
								"spirit_name":"sprites_2D_lable_i"
							},
							{
								"spirit_id":53,
								"spirit_name":"sprites_2D_lable_j"
							},
							{
								"spirit_id":54,
								"spirit_name":"sprites_2D_lable_k"
							},
							{
								"spirit_id":55,
								"spirit_name":"sprites_2D_lable_l"
							},
							{
								"spirit_id":56,
								"spirit_name":"sprites_2D_lable_m"
							},
							{
								"spirit_id":57,
								"spirit_name":"sprites_2D_lable_n"
							},
							{
								"spirit_id":58,
								"spirit_name":"sprites_2D_lable_o"
							},
							{
								"spirit_id":59,
								"spirit_name":"sprites_2D_lable_p"
							},
							{
								"spirit_id":60,
								"spirit_name":"sprites_2D_lable_q"
							},
							{
								"spirit_id":61,
								"spirit_name":"sprites_2D_lable_r"
							},
							{
								"spirit_id":62,
								"spirit_name":"sprites_2D_lable_s"
							},
							{
								"spirit_id":63,
								"spirit_name":"sprites_2D_lable_t"
							},
							{
								"spirit_id":64,
								"spirit_name":"sprites_2D_lable_u"
							},
							{
								"spirit_id":65,
								"spirit_name":"sprites_2D_lable_v"
							},
							{
								"spirit_id":66,
								"spirit_name":"sprites_2D_lable_w"
							},
							{
								"spirit_id":67,
								"spirit_name":"sprites_2D_lable_x"
							},
							{
								"spirit_id":68,
								"spirit_name":"sprites_2D_lable_y"
							},
							{
								"spirit_id":69,
								"spirit_name":"sprites_2D_lable_z"
							},
							{
								"spirit_id":70,
								"spirit_name":"sprites_2D_lable_other"
							}

				]
			},
			{
				"id":4,
				"name":"infobox", 
				"spirits":[ 
						
					
							{
								"spirit_id":43,
								"spirit_name":"sprites_2D_icon_sprites_2"
							},
							{
								"spirit_id":71,
								"spirit_name":"sprites_2D_background_4" 
							},
							{
								"spirit_id":72,
								"spirit_name":"sprites_2D_icon_ball_1"
							},
							{
								"spirit_id":73,
								"spirit_name":"sprites_2D_icon_white_label_1"
							},
							{
								"spirit_id":74,
								"spirit_name":"sprites_2D_box_title"
							},
							{
								"spirit_id":75,
								"spirit_name":"sprites_2D_info_box_1"
							},
							{
								"spirit_id":76,
								"spirit_name":"sprites_2D_info_box_2"
							},
							{
								"spirit_id":77,
								"spirit_name":"sprites_2D_info_box_3"
							},
							{
								"spirit_id":78,
								"spirit_name":"sprites_2D_info_box_4"
							},
							{
								"spirit_id":79,
								"spirit_name":"sprites_2D_info_box_5"
							},
							{
								"spirit_id":80,
								"spirit_name":"sprites_2D_info_box_6"
							}

				]
			},
			{
				"id":5,
				"name":"ContactShortCut", 
				"spirits":[ 
							{
								"spirit_id":35000,
								"spirit_name":"sprites_2D_background_1" 
							},
						
							{
								"spirit_id":1,
								"spirit_name":"sprites_2D_background_1" 
							},
							{
								"spirit_id":2,
								"spirit_name":"sprites_2D_background_2"
							},
							{
								"spirit_id":3,
								"spirit_name":"sprites_2D_heart_1"
							},
							{
								"spirit_id":4,
								"spirit_name":"sprites_2D_flower_1"
							},
							{
								"spirit_id":5,
								"spirit_name":"sprites_2D_flower_top"
							},
							{
								"spirit_id":6,
								"spirit_name":"sprites_2D_butterfly_1"
							},
							{
								"spirit_id":7,
								"spirit_name":"sprites_2D_curtain_1"
							},
							{
								"spirit_id":8,
								"spirit_name":"sprites_2D_flower_right_1"
							},
							{
								"spirit_id":9,
								"spirit_name":"sprites_2D_icon_red_1"
							},
							{
								"spirit_id":10,
								"spirit_name":"sprites_2D_icon_red_2"
							},
							{
								"spirit_id":11,
								"spirit_name":"sprites_2D_icon_red_3"
							},
							{
								"spirit_id":12,
								"spirit_name":"sprites_2D_icon_red_4"
							},
							{
								"spirit_id":13,
								"spirit_name":"sprites_2D_icon_red_5"
							},
							{
								"spirit_id":14,
								"spirit_name":"sprites_2D_icon_red_6"
							},
							{
								"spirit_id":15,
								"spirit_name":"sprites_2D_icon_red_7"
							},
							{
								"spirit_id":16,
								"spirit_name":"sprites_2D_icon_red_8"
							},
							{
								"spirit_id":17,
								"spirit_name":"sprites_2D_label_red_1"
							},
							{
								"spirit_id":18,
								"spirit_name":"sprites_2D_label_red_2"
							},
							{
								"spirit_id":19,
								"spirit_name":"sprites_2D_label_white_1"
							},
							{
								"spirit_id":20,
								"spirit_name":"sprites_2D_label_white_2"
							},
							{
								"spirit_id":21,
								"spirit_name":"sprites_2D_box_yellow"
							},
							{
								"spirit_id":22,
								"spirit_name":"sprites_2D_box_red"
							},
							{
								"spirit_id":82,
								"spirit_name":"sprites_2D_icon_sprites_2"
							},
							{
								"spirit_id":83,
								"spirit_name":"sprites_2D_background_4" 
							},
							{
								"spirit_id":84,
								"spirit_name":"sprites_2D_icon_ball_1"
							},
							{
								"spirit_id":85,
								"spirit_name":"sprites_2D_icon_white_label_1"
							},
							{
								"spirit_id":86,
								"spirit_name":"sprites_2D_box_title"
							},
							{
								"spirit_id":87,
								"spirit_name":"sprites_2D_info_box_1"
							},
							{
								"spirit_id":88,
								"spirit_name":"sprites_2D_info_box_2"
							},
							{
								"spirit_id":89,
								"spirit_name":"sprites_2D_info_box_3"
							}
			

				]
			}
		]
}